#!/bin/bash

set -e

echo "Creating output directory _out...";
rm -rf _out && mkdir _out;

echo "Copying site files...";
cp index.html _out/;

echo "Creating JS bundle...";
browserify main.js -t [ babelify --presets [react] ] | uglifyjs > _out/bundle.js;

echo "Done!";
