#!/bin/bash

set -e

echo "Creating output directory _out...";
rm -rf _out && mkdir _out;

echo "Copying site files...";
cp index.html _out/;

echo "Creating JS bundle...";
browserify main.js -t [ babelify --presets [react] ] | uglifyjs > _out/bundle.js;

echo "Converting sounds...";
mkdir -p _out/assets/audio/converted;
cd assets/audio && mkdir -p converted;
find . -iname "*.wav" | while read infile; do
  outfile="./converted/${infile%%.wav}.mp3";
  ffmpeg -nostdin -i $infile $outfile -y;
  cp $outfile ../../_out/assets/audio/converted/;
done

echo "Done!";
