#!/bin/bash
# Install a recent version of ffmpeg on Ubuntu 12.04 64bit (which is what Travis
# CI runs)

set -e

wget http://johnvansickle.com/ffmpeg/builds/ffmpeg-git-64bit-static.tar.xz -O /tmp/ffmpeg.tar.xz
tar -xJf /tmp/ffmpeg.tar.xz

# The downloaded ffmpeg binary will be in a dir which we can't be sure of the name
# of. Since we need this in a known place for the other scripts to run properly find
# the dir that was downloaded and rename it to 'ffmpeg'.
find . -maxdepth 1 -iname "ffmpeg*" | head -n 1 | while read fp; do
  mv "$fp" ./ffmpeg
done
